---
# Install Spark on YARN
# Redhat / CentOS
- name: Install mapr-spark (Redhat / CentOS)
  yum: name=mapr-spark state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-spark (Debian / Ubuntu)
  apt: name=mapr-spark state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-spark (Suse)
  zypper: name=mapr-spark state=present
  when: ansible_os_family == 'Suse'

# Other actions
#- name: Set SPARK_HOME for user root
#  shell: export SPARK_HOME=/opt/mapr/spark/$(ls /opt/mapr/spark/|grep spark-)/
#- name: Set SPARK_HOME for user mapr
#  shell: su mapr -c "export SPARK_HOME=/opt/mapr/spark/$(ls /opt/mapr/spark/|grep spark-)/"

- name: Create maprfs:///apps/spark
  shell: hadoop fs -mkdir -p /apps/spark
- name: Owner maprfs:///apps/spark
  shell: hadoop fs -chown mapr:mapr /apps/spark
- name: Chmod 777 /apps/spark
  shell: hadoop fs -chmod 777 /apps/spark
- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
- name: Set owner mapr-system user
  file: path=/opt/mapr/spark owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes

- name: Create maprfs:///user/mapr
  shell: hadoop fs -mkdir -p /user/mapr
- name: Owner maprfs:///user/mapr
  shell: hadoop fs -chown mapr:mapr /user/mapr